version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: blacklake
      POSTGRES_USER: blacklake
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blacklake -d blacklake"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: blacklake
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    command: start-dev
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 30s
      timeout: 10s
      retries: 5

  blacklake-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 8080
      RUST_LOG: info,blacklake=debug
      DATABASE_URL: postgres://blacklake:${POSTGRES_PASSWORD}@postgres:5432/blacklake
      S3_ENDPOINT: http://minio:9000
      S3_REGION: us-east-1
      S3_BUCKET: blacklake
      S3_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      S3_SECRET_KEY: ${MINIO_SECRET_KEY}
      S3_FORCE_PATH_STYLE: "true"
      OIDC_ISSUER: http://keycloak:8080/realms/master
      OIDC_AUDIENCE: blacklake
      RATE_LIMIT_RPM: 1000
      RATE_LIMIT_BURST: 100
      RATE_LIMIT_PER_USER: 5000
      RATE_LIMIT_PER_IP: 2000
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/live"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  blacklake-cli:
    build:
      context: .
      dockerfile: Dockerfile.cli
    environment:
      BLACKLAKE_API_URL: http://blacklake-api:8080
    depends_on:
      blacklake-api:
        condition: service_healthy
    profiles:
      - cli

volumes:
  postgres_data:
  minio_data:
