site_name: BlackLake Documentation
site_description: BlackLake Data Artifact Management Platform Documentation
site_author: BlackLake Team
site_url: https://blacklake.github.io/blacklake

# Repository
repo_name: blacklake/blacklake
repo_url: https://github.com/blacklake/blacklake
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

# Plugins
plugins:
  - search:
      lang: en
  - mermaid2:
      arguments:
        theme: default
        themeVariables:
          primaryColor: '#1976d2'
          primaryTextColor: '#000000'
          primaryBorderColor: '#1976d2'
          lineColor: '#000000'
          secondaryColor: '#f0f0f0'
          tertiaryColor: '#ffffff'
  - git-revision-date-localized:
      enable_creation_date: true

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      title: On this page
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: blacklake
      repo: blacklake
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables

# Page tree
nav:
  - Home: index.md
  - Documentation: documentation.md
  - Getting Started:
    - getting-started.md
    - QUICK_START.md
    - local_testing.md
    - MIGRATION_SETUP.md
  - Architecture & Design:
    - architecture.md
    - PROJECT_STATUS.md
    - IMPLEMENTATION_SUMMARY.md
  - Operations:
    - DEPLOYMENT.md
    - OPERATIONS.md
    - ACTIVE_STANDBY_GUIDE.md
    - Runbooks:
      - ops/runbooks/backup-restore.md
      - ops/runbooks/disaster-recovery.md
      - ops/runbooks/security-incident.md
      - ops/runbooks/performance-troubleshooting.md
  - Features:
    - SEARCH.md
    - SESSIONS.md
    - IMAGES.md
  - Verification:
    - VERIFICATION.md
    - FAST_SETUP.md
  - Development:
    - TODO.md
    - CHANGELOG.md
    - cli.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/blacklake/blacklake
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/blacklake/blacklake
  version:
    provider: mike

# Copyright
copyright: Copyright &copy; 2024 BlackLake Team
