apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blacklake-prod

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - service-patch.yaml
  - ingress-patch.yaml
  - hpa-patch.yaml
  - pdb-patch.yaml

configMapGenerator:
  - name: blacklake-config
    literals:
      - API_BASE_URL=https://api.blacklake.dev
      - UI_BASE_URL=https://blacklake.dev
      - RUST_LOG=info
      - SESSION_TIMEOUT=3600
      - RATE_LIMIT_REQUESTS=1000
      - RATE_LIMIT_WINDOW=3600

secretGenerator:
  - name: blacklake-secrets
    literals:
      - database-url=postgresql://blacklake:${DB_PASSWORD}@postgresql:5432/blacklake
      - redis-url=redis://redis:6379
      - solr-url=http://solr:8983
      - s3-endpoint=https://s3.amazonaws.com
      - s3-access-key-id=${AWS_ACCESS_KEY_ID}
      - s3-secret-access-key=${AWS_SECRET_ACCESS_KEY}
      - s3-bucket=blacklake-prod
      - jwt-secret=${JWT_SECRET}

commonLabels:
  environment: prod
  app.kubernetes.io/part-of: blacklake-prod
