apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: blacklake
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: blacklake
      app.kubernetes.io/instance: blacklake
