# OpenTelemetry Collector Configuration for BlackLake
# Week 5: Observability and monitoring

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

  prometheus:
    config:
      scrape_configs:
        - job_name: 'blacklake-api'
          static_configs:
            - targets: ['api:8080']
          metrics_path: '/metrics'
          scrape_interval: 15s

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
    send_batch_max_size: 2048

  memory_limiter:
    limit_mib: 512
    spike_limit_mib: 128
    check_interval: 5s

  resource:
    attributes:
      - key: service.name
        value: blacklake
        action: upsert
      - key: service.version
        value: "1.0.0"
        action: upsert
      - key: deployment.environment
        value: ${DEPLOYMENT_ENVIRONMENT:-development}
        action: upsert

  attributes:
    actions:
      - key: http.request.method
        action: insert
        from_attribute: http.method
      - key: http.response.status_code
        action: insert
        from_attribute: http.status_code

exporters:
  # Console exporter for development
  logging:
    loglevel: info
    sampling_initial: 2
    sampling_thereafter: 500

  # Prometheus exporter for metrics
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: blacklake
    const_labels:
      service: blacklake
      version: "1.0.0"

  # OTLP exporter for external systems
  otlp:
    endpoint: ${OTLP_ENDPOINT:-http://jaeger:14250}
    tls:
      insecure: true

  # Jaeger exporter for tracing
  jaeger:
    endpoint: ${JAEGER_ENDPOINT:-jaeger:14250}
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource, attributes]
      exporters: [logging, jaeger, otlp]

    metrics:
      receivers: [otlp, prometheus]
      processors: [memory_limiter, batch, resource]
      exporters: [logging, prometheus]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, resource]
      exporters: [logging]

  extensions: []
