# BlackLake Helm Chart Values
# Week 7: Enterprise hardening and scale

# Global configuration
global:
  imageRegistry: ""
  imagePullSecrets: []
  storageClass: ""

# Image configuration
image:
  registry: docker.io
  repository: blacklake/blacklake
  tag: "latest"
  pullPolicy: IfNotPresent

# Image pull secrets
imagePullSecrets: []

# Service account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# Pod security context
podSecurityContext:
  fsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000

# Container security context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

# Service configuration
service:
  type: ClusterIP
  port: 8080
  targetPort: 8080
  annotations: {}

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: blacklake.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Resource limits and requests
resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

# Autoscaling configuration
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

# Pod disruption budget
podDisruptionBudget:
  enabled: true
  minAvailable: 1

# Topology spread constraints
topologySpreadConstraints:
  enabled: true
  maxSkew: 1
  topologyKey: kubernetes.io/hostname
  whenUnsatisfiable: DoNotSchedule

# Health checks
livenessProbe:
  httpGet:
    path: /live
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /ready
    port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Environment variables
env:
  - name: RUST_LOG
    value: "info"
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: blacklake-secrets
        key: database-url
  - name: REDIS_URL
    valueFrom:
      secretKeyRef:
        name: blacklake-secrets
        key: redis-url
  - name: SOLR_URL
    valueFrom:
      secretKeyRef:
        name: blacklake-secrets
        key: solr-url
  - name: S3_ENDPOINT
    valueFrom:
      secretKeyRef:
        name: blacklake-secrets
        key: s3-endpoint
  - name: S3_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: blacklake-secrets
        key: s3-access-key-id
  - name: S3_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: blacklake-secrets
        key: s3-secret-access-key
  - name: S3_BUCKET
    valueFrom:
      secretKeyRef:
        name: blacklake-secrets
        key: s3-bucket
  - name: JWT_SECRET
    valueFrom:
      secretKeyRef:
        name: blacklake-secrets
        key: jwt-secret

# ConfigMap for non-sensitive configuration
configMap:
  create: true
  data:
    API_BASE_URL: "http://localhost:8080"
    UI_BASE_URL: "http://localhost:3000"
    SESSION_TIMEOUT: "3600"
    RATE_LIMIT_REQUESTS: "1000"
    RATE_LIMIT_WINDOW: "3600"

# Secrets configuration
secrets:
  create: true
  data: {}

# Persistence configuration
persistence:
  enabled: false
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi

# Node selector
nodeSelector: {}

# Tolerations
tolerations: []

# Affinity
affinity: {}

# Pod annotations
podAnnotations: {}

# Pod labels
podLabels: {}

# Service monitor for Prometheus
serviceMonitor:
  enabled: true
  namespace: ""
  interval: 30s
  scrapeTimeout: 10s
  labels: {}
  annotations: {}

# Grafana dashboard
grafanaDashboard:
  enabled: true
  namespace: ""
  labels: {}
  annotations: {}

# Network policies
networkPolicy:
  enabled: false
  ingress: []
  egress: []

# Horizontal Pod Autoscaler
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max

# Vertical Pod Autoscaler
vpa:
  enabled: false
  updateMode: "Auto"
  resourcePolicy:
    cpu:
      min: 100m
      max: 1000m
    memory:
      min: 128Mi
      max: 2Gi

# Dependencies
postgresql:
  enabled: true
  auth:
    postgresPassword: "postgres"
    database: "blacklake"
  primary:
    persistence:
      enabled: true
      size: 20Gi
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi

redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi

solr:
  enabled: true
  auth:
    enabled: false
  persistence:
    enabled: true
    size: 20Gi
  resources:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
